# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2c6dc60d0c86d32c71aa2ec2ae1fff32f338187ceaa12f0d6a294f368760ead01bc1c57115d48b80ab4042b45ca5aceadea1e888f34b5a14ab548eb07e1ad9c
  # user: 'partner@atgpartner.ru'
  # pwd:  '120160xx'
  # key: "atgpartnerkey"
  user: ENV["user"]
  pwd:  ENV["pwd"]
  key:  ENV["key"]
test:
  secret_key_base: f4c0aad565527a57110ccba77def71e2dd1b65799b94d4d24f9b34a8bc42fd01dbc64349c5555dca46b4d5d2ba85f890c718c1de0d20237704c788e4db928c66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_token:  ENV["secret_token"]
  secret_key_base:  ENV["secret_key_base"]
  user: ENV["user"]
  pwd:   ENV["pwd"] 
  key:  ENV["key"]

